name: Run AFK Bot
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [keep_alive]

jobs:
  afk-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Mineflayer
        run: npm install mineflayer
      - name: Run Bot
        run: |
          node -e "
          const mineflayer = require('mineflayer');
          const bot = mineflayer.createBot({
            host: 'VengefulBattle.play.hosting',
            username: 'Devil_Bot',
            version: '1.21.1',
            hideErrors: true
          });
          bot.on('spawn', () => {
            console.log('Bot Active');
            bot.physicsEnabled = false;
          });
          setTimeout(() => { process.exit(0); }, 900000);
          "
