name: Run AFK Bot
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  join:
    runs-on: ubuntu-latest
    steps:
      - name: Start Bot
        uses: dscalzi/mineflayer-afk-action@v1
        with:
          host: "VengefulBattle.play.hosting"
          username: "Devil_Bot"
          version: "1.21.1"
